Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,6 +24,10 @@ runs:
       env:
         CONTEXT: ${{ toJson(github) }}
 
+    - name: "secrets?"
+      run: [[ "foo" == "${{ secrets.FOO }}" ]] || echo "cannot read"
+      shell: bash
+
     - name: show files
       run: ls -la
       shell: bash
